#!/bin/bash

# Get the current owner of the file 'hello'
current_owner=$(stat -c '%U' hello)

# Check if the current owner is 'guillaume'
if [ "$current_owner" == "guillaume" ]; then
  # Change the owner to 'vincent'
  chown vincent hello
fi
